# Generated by Django 5.2.7 on 2025-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XrplWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(max_length=35, unique=True)),
                ('balance', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
            ],
        ),
    ]
